export const Colors = {
  primary: '#2E7D32',
  primaryLight: '#E8F5E9',
  primaryDark: '#1B5E20',
  accent: '#F5A623',
  accentLight: '#FFF3E0',
  background: '#FAF8F5',
  surface: '#FFFFFF',
  bubbleAssistant: '#FFFFFF',
  bubbleUser: '#E4F5D4',
  textPrimary: '#1A1A1A',
  textSecondary: '#757575',
  textOnPrimary: '#FFFFFF',
  inputBackground: '#FFFFFF',
  inputBorder: '#E8E4DE',
  typingDot: '#BDBDBD',
  error: '#C62828',
  errorLight: '#FFEBEE',
  headerBackground: '#2E7D32',
  headerText: '#FFFFFF',
  separator: '#E8E4DE',
  chipBackground: '#E8F5E9',
  chipBorder: '#A5D6A7',
  chipText: '#2E7D32',
  shadow: '#000000',
};
