export const Colors = {
  primary: '#2E7D32',
  primaryLight: '#E8F5E9',
  primaryDark: '#1B5E20',
  accent: '#FF6F00',
  background: '#F5F5F5',
  surface: '#FFFFFF',
  bubbleAssistant: '#FFFFFF',
  bubbleUser: '#DCF8C6',
  textPrimary: '#1A1A1A',
  textSecondary: '#757575',
  textOnPrimary: '#FFFFFF',
  inputBackground: '#FFFFFF',
  inputBorder: '#E0E0E0',
  typingDot: '#BDBDBD',
  error: '#C62828',
  errorLight: '#FFEBEE',
  headerBackground: '#2E7D32',
  headerText: '#FFFFFF',
  separator: '#E0E0E0',
  chipBackground: '#E8F5E9',
  chipBorder: '#A5D6A7',
  chipText: '#2E7D32',
  shadow: '#000000',
};
